package com.email.assistant.ai;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@Service
public class GeminiService {

    @Value("${gemini.api.key}")
    private String apiKey;

    @Value("${gemini.api.url}")
    private String apiUrl;

    private final RestTemplate restTemplate = new RestTemplate();

    public String generateEmail(
            String prompt,
            String tone,
            String length) {

        String instruction = String.format(
                """
                Write a professional email.

                Request: %s

                Tone: %s

                Length: %s

                Return only the email content.
                Do not add explanations.
                """,
                prompt,
                tone,
                length
        );

        return callGemini(instruction);
    }

    public String regenerateEmail(
            String prompt,
            String tone,
            String length) {

        return generateEmail(
                prompt,
                tone,
                length
        );
    }

    private String callGemini(String prompt) {

        Map<String, Object> textPart = new HashMap<>();
        textPart.put("text", prompt);

        Map<String, Object> content = new HashMap<>();
        content.put(
                "parts",
                Collections.singletonList(textPart)
        );

        Map<String, Object> requestBody = new HashMap<>();
        requestBody.put(
                "contents",
                Collections.singletonList(content)
        );

        HttpHeaders headers = new HttpHeaders();

        headers.setContentType(
                MediaType.APPLICATION_JSON
        );

        headers.set(
                "x-goog-api-key",
                apiKey
        );

        HttpEntity<Map<String, Object>> entity =
                new HttpEntity<>(
                        requestBody,
                        headers
                );

        ResponseEntity<Map> response =
                restTemplate.postForEntity(
                        apiUrl,
                        entity,
                        Map.class
                );

        if (!response.getStatusCode().is2xxSuccessful()
                || response.getBody() == null) {

            throw new RuntimeException(
                    "Gemini API request failed"
            );
        }

        Map body = response.getBody();

        List candidates =
                (List) body.get("candidates");

        if (candidates == null ||
                candidates.isEmpty()) {

            throw new RuntimeException(
                    "No response generated by Gemini"
            );
        }

        Map candidate =
                (Map) candidates.get(0);

        Map contentResponse =
                (Map) candidate.get("content");

        List parts =
                (List) contentResponse.get("parts");

        if (parts == null ||
                parts.isEmpty()) {

            throw new RuntimeException(
                    "Gemini returned empty content"
            );
        }

        Map firstPart =
                (Map) parts.get(0);

        return String.valueOf(
                firstPart.get("text")
        );
    }
}