server.port=8097

# ==============================
# MYSQL
# ==============================

spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/email_assistant}
spring.datasource.username=${DATABASE_USERNAME:root}
spring.datasource.password=${DATABASE_PASSWORD:}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==============================
# JPA
# ==============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# ==============================
# JWT
# ==============================

spring.jpa.open-in-view=false
jwt.secret=${JWT_SECRET:}
jwt.expiration=${JWT_EXPIRATION:86400000}

# ==============================
# GEMINI
# ==============================

gemini.api.key=${GEMINI_API_KEY:}
gemini.api.url=${GEMINI_API_URL:https://generativelanguage.googleapis.com/v1beta/models/gemini-3.6-flash:generateContent}
frontend.url=${FRONTEND_URL:http://localhost:5173}
